### ISSUE TITLE
Make a package for hackage

### ISSUE THREAD

**Issue by Josef-Thorne-A** [cdepillabout/focuslist#1]
The library now builds independently with all the features it has in its original termonad implementation. All tests pass. 

@cdepillabout

**Comment by cdepillabout** [comment]
Just uploaded to Hackage!

http://hackage.haskell.org/package/focuslist-0.1.0.0

@Grendel-Grendel-Grendel If you give me your username on Hackage, I will add you to the maintainers list for `focuslist`.  This will enable you to upload future versions of `focuslist` to Hackage. (If you don't yet have an account on Hackage, please create one!)

So now you'll be in charge of future releases.  Please follow the release checklist when making future releases:

https://functor.tokyo/blog/2018-07-16-release-haskell-packages-to-hackage

Please feel free to make future releases when you deem it necessary, or when a user requests it.

Also, do you use `stack`?  If so, could you get `focuslist` into stackage?

**Comment by gwils** [comment]
Can you please make a new release that includes the changes from #3 now that that's merged?

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel Could you make a release from the current master branch to Hackage following the [checklist](https://functor.tokyo/blog/2018-07-16-release-haskell-packages-to-hackage)?

**Comment by Josef-Thorne-A** [comment]
Apologies for the delay, some stuff came up in real life for a bit and I didn't have time to tend to this. I'm going to get to this now.

**Comment by cdepillabout** [comment]
@Grendel-Grendel-Grendel Thanks for making a release!

@gwils Here's the new version:

http://hackage.haskell.org/package/focuslist-0.1.0.1
